export type SearchResponse = {
  numFound: number;
  start: number;
  numFoundExact: boolean;
  docs: Array<{
    title: string;
    author_name: Array<string> | undefined;
    key: string;
    cover_i: number | undefined;
    isbn: Array<string> | undefined;
    first_publish_year: number | undefined;
    publish_date: Array<string> | undefined;
  }>;
};

export type OpenLibraryWork = {
  title: string;
  authors?: Array<{
    author: { key: string };
  }>;
  covers: number[];
  key: string;
  description?: { value: string } | string;
  subjects?: string[];
  subject_people?: string[];
  subject_places?: string[];
  subject_times?: string[];
  first_sentence?: { value: string };
};

export type Edition = {
  notes?: {
    value: string;
  };
  works: Array<{ key: string }>;
  publish_date?: string;
  publishers?: string[];
  title: string;
  full_title?: string;
  subtitle?: string;
  covers?: number[];
  key: string;
  number_of_pages?: number;
};

export type EditionsResponse = {
  size: number;
  entries: Edition[];
};

export type Ratings = {
  summary?: { average: number; count: number };
};

export type OpenLibrarySubject = {
  name: string;
  key: string;
  works?: Array<{
    key: string;
    title: string;
    cover_id?: number | undefined;
    authors?: Array<{ name: string }>;
  }>;
  subjects?: Array<{ key: string; name: string }>;
  places?: Array<{ key: string; name: string }>;
  times?: Array<{ key: string; name: string }>;
  authors?: Array<{ name: string }>;
};

export const fakeSubject = {
  key: "/subjects/dark_romance",
  name: "dark romance",
  subject_type: "subject",
  work_count: 177,
  works: [
    {
      key: "/works/OL4996160W",
      title: "Sweet Savage Love:(Brandon-Morgan #1)",
      edition_count: 20,
      cover_id: 234725,
      cover_edition_key: "OL7431249M",
      subject: [
        "Dark romance",
        "Romance",
        "spy",
        "alpha male",
        "Western Romance",
        "Bodice ripper",
        "Fiction",
        "Historical Fiction",
        "Brandon-Morgan Series",
        "Historical Romance",
        "Fiction, romance, historical",
        "Fiction, romance, general",
        "Fiction, romance, historical, general",
        "collectionID:Abodice_ripper",
      ],
      ia_collection: [
        "americana",
        "inlibrary",
        "internetarchivebooks",
        "openlibrary-d-ol",
        "printdisabled",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL39797563M",
      lending_identifier: "amourtendreamour0000roge",
      authors: [
        {
          key: "/authors/OL1081479A",
          name: "Rosemary Rogers",
        },
      ],
      first_publish_year: 1974,
      ia: "amourtendreamour0000roge",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "amourtendreamour0000roge",
        isbn: "2277119520",
        oclc: null,
        openlibrary_work: "OL28943660W",
        openlibrary_edition: "OL39797563M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL24390422W",
      title: "Twisted Love",
      edition_count: 13,
      cover_id: 12940491,
      cover_edition_key: "OL37985553M",
      subject: [
        "Fiction, romance, multicultural & interracial",
        "Fiction, romance, new adult",
        "Fiction, romance, contemporary",
        "nyt:combined-print-and-e-book-fiction=2023-07-02",
        "New York Times bestseller",
        "Romance",
        "contemporary romance",
        "new adult romance",
        "brother's best friend",
        "forbidden love",
        "dark romance",
        "grumpy-sunshine",
        "angst",
        "love triangle",
        "self-discovery",
        "redemption",
      ],
      ia_collection: [""],
      lendinglibrary: false,
      printdisabled: false,
      lending_edition: "",
      lending_identifier: "",
      authors: [
        {
          key: "/authors/OL9180803A",
          name: "Ana Huang",
        },
      ],
      first_publish_year: 2021,
      ia: null,
      public_scan: false,
      has_fulltext: false,
    },
    {
      key: "/works/OL4996158W",
      title: "The Wanton",
      edition_count: 10,
      cover_id: 8315240,
      cover_edition_key: "OL2543036M",
      subject: [
        "Dark romance",
        "alpha male",
        "History",
        "Love stories",
        "Fiction",
        "Louisiana",
        "Civil War",
        "Large type books",
        "Fiction, romance, historical",
        "United states, history, civil war, 1861-1865, fiction",
        "Bodice Ripper",
        "Western Romance",
        "Historical Romance",
        "Fiction, romance, historical, general",
        "collectionID:Abodice_ripper",
      ],
      ia_collection: [
        "americana",
        "inlibrary",
        "internetarchivebooks",
        "openlibrary-d-ol",
        "printdisabled",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL22911168M",
      lending_identifier: "wantonrog00roge",
      authors: [
        {
          key: "/authors/OL1081479A",
          name: "Rosemary Rogers",
        },
      ],
      first_publish_year: 1843,
      ia: "wantonrog00roge",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: true,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "wantonrog00roge",
        isbn: "0380861658",
        oclc: null,
        openlibrary_work: "OL4996158W",
        openlibrary_edition: "OL22911168M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL3759118W",
      title: "Love's Choices (Worldwide Library, Signature ed., No. 1)",
      edition_count: 10,
      cover_id: 4608744,
      cover_edition_key: null,
      subject: [
        "collectionID:Gbodice_ripper",
        "Fiction, romance, general",
        "Romance fiction",
        "Fiction, general",
        "Bodice ripper",
        "Dark romance",
      ],
      ia_collection: [
        "inlibrary",
        "internetarchivebooks",
        "openlibrary-d-ol",
        "printdisabled",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL7421947M",
      lending_identifier: "loveschoice0000jord",
      authors: [
        {
          key: "/authors/OL661093A",
          name: "Penny Jordan",
        },
      ],
      first_publish_year: 1984,
      ia: "loveschoice0000jord",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: false,
        available_to_waitlist: true,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "loveschoice0000jord",
        isbn: "037383327X",
        oclc: null,
        openlibrary_work: "OL3759326W",
        openlibrary_edition: "OL7421947M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL25515697W",
      title: "Twisted Games",
      edition_count: 10,
      cover_id: 12821465,
      cover_edition_key: "OL35082870M",
      subject: [
        "Romance",
        "contemporary romance",
        "romantic suspense",
        "new adult romance",
        "forbidden love",
        "bodyguard romance",
        "dark romance",
        "enemies to lovers",
        "slow burn",
        "angst",
        "steamy",
        "Fiction, romance, general",
        "Fiction, general",
      ],
      ia_collection: [""],
      lendinglibrary: false,
      printdisabled: false,
      lending_edition: "",
      lending_identifier: "",
      authors: [
        {
          key: "/authors/OL9180803A",
          name: "Ana Huang",
        },
      ],
      first_publish_year: 2021,
      ia: null,
      public_scan: false,
      has_fulltext: false,
    },
    {
      key: "/works/OL4996159W",
      title: "Dark Fires:(Brandon-Morgan #2)",
      edition_count: 9,
      cover_id: 234715,
      cover_edition_key: "OL7431098M",
      subject: [
        "collectionID:Abodice_ripper",
        "morgan series",
        "Bodice ripper",
        "alpha male",
        "Dark romance",
        "challenger series",
        "Romance",
        "Fiction",
        "Brandon-Morgan Series",
        "Romance fiction",
        "Historical Romance",
        "Fiction, romance, historical",
        "Fiction, romance, general",
        "Fiction, romance, historical, general",
      ],
      ia_collection: [
        "americana",
        "inlibrary",
        "internetarchivebooks",
        "openlibrary-d-ol",
        "printdisabled",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL19999097M",
      lending_identifier: "darkfires0000roge",
      authors: [
        {
          key: "/authors/OL1081479A",
          name: "Rosemary Rogers",
        },
      ],
      first_publish_year: 1975,
      ia: "darkfires0000roge",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "darkfires0000roge",
        isbn: "0860074595",
        oclc: null,
        openlibrary_work: "OL4996159W",
        openlibrary_edition: "OL19999097M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL5948224W",
      title: "The Lady's Tutor",
      edition_count: 9,
      cover_id: 505425,
      cover_edition_key: "OL8006227M",
      subject: [
        "collectionID:DHromance",
        "historical romance",
        "Fiction, romance, historical",
        "Great britain, social life and customs, fiction",
        "alpha male",
        "Dark romance",
        "Fiction, romance, general",
      ],
      ia_collection: [""],
      lendinglibrary: false,
      printdisabled: false,
      lending_edition: "",
      lending_identifier: "",
      authors: [
        {
          key: "/authors/OL1475106A",
          name: "Robin Schone",
        },
      ],
      first_publish_year: 1999,
      ia: null,
      public_scan: false,
      has_fulltext: false,
    },
    {
      key: "/works/OL4996154W",
      title: "Surrender to Love",
      edition_count: 8,
      cover_id: 771493,
      cover_edition_key: "OL8567417M",
      subject: [
        "Fiction, Romance, Historical",
        "Man-woman relationships, fiction",
        "Dark romance",
        "Americans",
        "Southern Romance",
        "Western Romance",
        "Bodice ripper",
      ],
      ia_collection: ["americana", "internetarchivebooks", "printdisabled"],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "",
      lending_identifier: "",
      authors: [
        {
          key: "/authors/OL1081479A",
          name: "Rosemary Rogers",
        },
      ],
      first_publish_year: 1982,
      ia: "surrendertolove0000roge_y8j2",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "private",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: false,
        is_previewable: true,
        identifier: "surrendertolove0000roge_y8j2",
        isbn: "0380806304",
        oclc: null,
        openlibrary_work: "OL4996154W",
        openlibrary_edition: "OL22939238M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL4996156W",
      title: "The Wildest Heart",
      edition_count: 7,
      cover_id: 234705,
      cover_edition_key: "OL7430955M",
      subject: [
        "collectionID:Wbodice_ripper",
        "Alpha Males",
        "Dark romance",
        "Apache",
        "Native American",
        "Western Romance",
        "Bodice Ripper",
        "Frontier and pioneer life in fiction",
        "Frontier and pioneer life",
        "Fiction",
        "Historical Romance",
        "Fiction, romance, historical",
        "Fiction, romance, general",
        "Romance",
        "Fiction, romance, historical, general",
        "New mexico, fiction",
        "Frontier and pioneer life, fiction",
      ],
      ia_collection: [
        "americana",
        "inlibrary",
        "internetarchivebooks",
        "openlibrary-d-ol",
        "printdisabled",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL23148073M",
      lending_identifier: "isbn_9781402222740",
      authors: [
        {
          key: "/authors/OL1081479A",
          name: "Rosemary Rogers",
        },
      ],
      first_publish_year: 1974,
      ia: "isbn_9781402222740",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: true,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "isbn_9781402222740",
        isbn: "9781402222740",
        oclc: null,
        openlibrary_work: "OL4996156W",
        openlibrary_edition: "OL23148073M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL27818823W",
      title: "Twisted Lies",
      edition_count: 7,
      cover_id: 14425197,
      cover_edition_key: null,
      subject: [
        "Romance",
        "suspense",
        "mystery",
        "thriller",
        "dark romance",
        "forbidden love",
        "enemies to lovers",
        "bad boy",
        "strong heroine",
        "college",
        "academia",
        "family drama",
        "secrets",
        "lies",
        "betrayal",
        "revenge",
        "American literature",
        "Fiction, romance, general",
        "Fiction, general",
      ],
      ia_collection: [""],
      lendinglibrary: false,
      printdisabled: false,
      lending_edition: "",
      lending_identifier: "",
      authors: [
        {
          key: "/authors/OL9180803A",
          name: "Ana Huang",
        },
        {
          key: "/authors/OL12616679A",
          name: "Mariona Gastó Jiménez",
        },
      ],
      first_publish_year: 2022,
      ia: null,
      public_scan: false,
      has_fulltext: false,
    },
    {
      key: "/works/OL4996153W",
      title: "Love Play",
      edition_count: 6,
      cover_id: 237161,
      cover_edition_key: "OL7435492M",
      subject: [
        "Fiction, romance, general",
        "Fiction",
        "Romance",
        "Motion picture industry",
        "alpha male",
        "Motion picture industry in fiction",
        "Large type books",
        "Dark romance",
        "Fiction, general",
        "Fiction, romance, contemporary",
      ],
      ia_collection: [
        "americana",
        "inlibrary",
        "internetarchivebooks",
        "openlibrary-d-ol",
        "printdisabled",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL4122814M",
      lending_identifier: "loveplay0000roge",
      authors: [
        {
          key: "/authors/OL1081479A",
          name: "Rosemary Rogers",
        },
      ],
      first_publish_year: 1981,
      ia: "loveplay0000roge",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "loveplay0000roge",
        isbn: "038077917X",
        oclc: null,
        openlibrary_work: "OL4996153W",
        openlibrary_edition: "OL4122814M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL31114600W",
      title: "Satan's Affair",
      edition_count: 6,
      cover_id: 13208844,
      cover_edition_key: "OL42748940M",
      subject: [
        "halloween",
        "reverse harem",
        "dark romance",
        "suspense",
        "vengeance",
        "horror",
      ],
      ia_collection: [""],
      lendinglibrary: false,
      printdisabled: false,
      lending_edition: "",
      lending_identifier: "",
      authors: [
        {
          key: "/authors/OL10218224A",
          name: "H. D. Carlton",
        },
      ],
      first_publish_year: 2021,
      ia: null,
      public_scan: false,
      has_fulltext: false,
    },
  ],
  subjects: [
    {
      key: "/subjects/contemporary",
      name: "contemporary",
      count: 68,
    },
    {
      key: "/subjects/alpha_male",
      name: "alpha male",
      count: 51,
    },
    {
      key: "/subjects/suspense",
      name: "suspense",
      count: 50,
    },
    {
      key: "/subjects/dark_romance",
      name: "Dark romance",
      count: 47,
    },
    {
      key: "/subjects/enemies_to_lovers",
      name: "enemies to lovers",
      count: 41,
    },
    {
      key: "/subjects/fiction",
      name: "Fiction",
      count: 37,
    },
    {
      key: "/subjects/fiction_romance_general",
      name: "Fiction, romance, general",
      count: 35,
    },
    {
      key: "/subjects/bdsm",
      name: "bdsm",
      count: 30,
    },
    {
      key: "/subjects/bully",
      name: "bully",
      count: 28,
    },
    {
      key: "/subjects/abuse",
      name: "abuse",
      count: 27,
    },
    {
      key: "/subjects/fiction_romance_historical_general",
      name: "Fiction, romance, historical, general",
      count: 26,
    },
    {
      key: "/subjects/historical_romance",
      name: "Historical Romance",
      count: 25,
    },
    {
      key: "/subjects/dual_pov",
      name: "dual pov",
      count: 25,
    },
    {
      key: "/subjects/forced_proximity",
      name: "forced proximity",
      count: 24,
    },
    {
      key: "/subjects/fiction_romance_historical",
      name: "Fiction, romance, historical",
      count: 23,
    },
    {
      key: "/subjects/rich_hero",
      name: "rich hero",
      count: 23,
    },
    {
      key: "/subjects/angst",
      name: "angst",
      count: 22,
    },
    {
      key: "/subjects/new_adult",
      name: "new adult",
      count: 22,
    },
    {
      key: "/subjects/collectioniddhromance",
      name: "collectionID:DHromance",
      count: 21,
    },
    {
      key: "/subjects/mafia",
      name: "mafia",
      count: 21,
    },
    {
      key: "/subjects/romance",
      name: "Romance",
      count: 20,
    },
    {
      key: "/subjects/possessive_hero",
      name: "possessive hero",
      count: 20,
    },
    {
      key: "/subjects/bodice_ripper",
      name: "Bodice Ripper",
      count: 19,
    },
    {
      key: "/subjects/dark_romance",
      name: "Dark Romance",
      count: 17,
    },
  ],
  places: [
    {
      key: "/subjects/place:england",
      name: "England",
      count: 13,
    },
    {
      key: "/subjects/place:london",
      name: "London",
      count: 10,
    },
    {
      key: "/subjects/place:france",
      name: "France",
      count: 4,
    },
    {
      key: "/subjects/place:london_(england)",
      name: "London (England)",
      count: 4,
    },
    {
      key: "/subjects/place:united_states",
      name: "United States",
      count: 4,
    },
    {
      key: "/subjects/place:india",
      name: "India",
      count: 3,
    },
    {
      key: "/subjects/place:mexico",
      name: "Mexico",
      count: 3,
    },
    {
      key: "/subjects/place:paris",
      name: "Paris",
      count: 3,
    },
    {
      key: "/subjects/place:america",
      name: "America",
      count: 2,
    },
    {
      key: "/subjects/place:egypt",
      name: "Egypt",
      count: 2,
    },
    {
      key: "/subjects/place:great_britain",
      name: "Great Britain",
      count: 2,
    },
    {
      key: "/subjects/place:italy",
      name: "Italy",
      count: 2,
    },
    {
      key: "/subjects/place:paris_(france)",
      name: "Paris (France)",
      count: 2,
    },
    {
      key: "/subjects/place:scotland",
      name: "Scotland",
      count: 2,
    },
    {
      key: "/subjects/place:texas",
      name: "Texas",
      count: 2,
    },
    {
      key: "/subjects/place:alta",
      name: "Alta",
      count: 1,
    },
    {
      key: "/subjects/place:boston",
      name: "Boston",
      count: 1,
    },
    {
      key: "/subjects/place:boston_(mass.)",
      name: "Boston (Mass.)",
      count: 1,
    },
    {
      key: "/subjects/place:california",
      name: "California",
      count: 1,
    },
    {
      key: "/subjects/place:ceylon",
      name: "Ceylon",
      count: 1,
    },
    {
      key: "/subjects/place:ceylon__sri_lanka",
      name: "Ceylon / Sri Lanka",
      count: 1,
    },
    {
      key: "/subjects/place:china",
      name: "China",
      count: 1,
    },
    {
      key: "/subjects/place:colorado",
      name: "Colorado",
      count: 1,
    },
    {
      key: "/subjects/place:devon_(england)",
      name: "Devon (England)",
      count: 1,
    },
    {
      key: "/subjects/place:edinburgh",
      name: "Edinburgh",
      count: 1,
    },
  ],
  times: [
    {
      key: "/subjects/time:victorian_era",
      name: "Victorian Era",
      count: 4,
    },
    {
      key: "/subjects/time:19th_century",
      name: "19th century",
      count: 3,
    },
    {
      key: "/subjects/time:civil_war_1861-1865",
      name: "Civil War, 1861-1865",
      count: 2,
    },
    {
      key: "/subjects/time:1753",
      name: "1753",
      count: 1,
    },
    {
      key: "/subjects/time:1763",
      name: "1763",
      count: 1,
    },
    {
      key: "/subjects/time:1768",
      name: "1768",
      count: 1,
    },
    {
      key: "/subjects/time:1800",
      name: "1800",
      count: 1,
    },
    {
      key: "/subjects/time:1800's",
      name: "1800's",
      count: 1,
    },
    {
      key: "/subjects/time:1833",
      name: "1833",
      count: 1,
    },
    {
      key: "/subjects/time:1861-1865",
      name: "1861-1865",
      count: 1,
    },
    {
      key: "/subjects/time:1872-1876",
      name: "1872-1876",
      count: 1,
    },
    {
      key: "/subjects/time:19th_century_1845",
      name: "19th Century; 1845+",
      count: 1,
    },
    {
      key: "/subjects/time:500–1450_ad",
      name: "500–1450 AD",
      count: 1,
    },
    {
      key: "/subjects/time:american_civil_war.",
      name: "American Civil War.",
      count: 1,
    },
    {
      key: "/subjects/time:civil_war",
      name: "Civil War",
      count: 1,
    },
    {
      key: "/subjects/time:franco-mexican_war",
      name: "Franco-Mexican War",
      count: 1,
    },
    {
      key: "/subjects/time:georgian",
      name: "Georgian",
      count: 1,
    },
    {
      key: "/subjects/time:medieval",
      name: "Medieval",
      count: 1,
    },
    {
      key: "/subjects/time:regency",
      name: "Regency",
      count: 1,
    },
    {
      key: "/subjects/time:regency_era",
      name: "Regency Era",
      count: 1,
    },
    {
      key: "/subjects/time:present_day",
      name: "present day",
      count: 1,
    },
  ],
  authors: [
    {
      name: "Clarissa Wild",
      key: "/authors/OL7931499A",
      count: 24,
    },
    {
      name: "Rosemary Rogers",
      key: "/authors/OL1081479A",
      count: 17,
    },
    {
      name: "Shantel Tessier",
      key: "/authors/OL8106346A",
      count: 15,
    },
    {
      name: "Veronica Eden",
      key: "/authors/OL10174581A",
      count: 8,
    },
    {
      name: "Kady Ash",
      key: "/authors/OL12724998A",
      count: 7,
    },
    {
      name: "Harley Laroux",
      key: "/authors/OL9466900A",
      count: 6,
    },
    {
      name: "Penelope Douglas",
      key: "/authors/OL11182351A",
      count: 5,
    },
    {
      name: "Kinsley Kincaid",
      key: "/authors/OL13677127A",
      count: 5,
    },
    {
      name: "H. D. Carlton",
      key: "/authors/OL10218224A",
      count: 4,
    },
    {
      name: "Leigh Rivers",
      key: "/authors/OL13680540A",
      count: 4,
    },
    {
      name: "Robin Schone",
      key: "/authors/OL1475106A",
      count: 4,
    },
    {
      name: "Sylvain Reynard",
      key: "/authors/OL7161547A",
      count: 4,
    },
    {
      name: "Kerrigan Byrne",
      key: "/authors/OL7540250A",
      count: 4,
    },
    {
      name: "S.T. Abby",
      key: "/authors/OL10140810A",
      count: 3,
    },
    {
      name: "Mika D. Mon",
      key: "/authors/OL10211395A",
      count: 3,
    },
    {
      name: "RuNyx",
      key: "/authors/OL13616822A",
      count: 3,
    },
    {
      name: "Bonnie Vanak",
      key: "/authors/OL1386239A",
      count: 3,
    },
    {
      name: "Kresley Cole",
      key: "/authors/OL1422827A",
      count: 3,
    },
    {
      name: "Lolah Burford",
      key: "/authors/OL1758074A",
      count: 3,
    },
    {
      name: "Marilyn Harris",
      key: "/authors/OL2688764A",
      count: 3,
    },
    {
      name: "Mara Laue",
      key: "/authors/OL8221267A",
      count: 3,
    },
    {
      name: "Ana Huang",
      key: "/authors/OL9180803A",
      count: 3,
    },
    {
      name: "Layla Moon",
      key: "/authors/OL14089671A",
      count: 2,
    },
    {
      name: "Patricia Gaffney",
      key: "/authors/OL31295A",
      count: 2,
    },
    {
      name: "Rachel Cosgrove Payes",
      key: "/authors/OL607112A",
      count: 2,
    },
  ],
};
