import Navbar from "@/src/components/Navbar";
import ReactQueryProvider from "@/src/utils/Provider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-zinc-700`}>
        <ReactQueryProvider>
          <Toaster position="bottom-right" />
          <Navbar />
          {children}
          <div id="modal" />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
