import { LogoIcon, MenuIcon } from "@/src/components/icons";
import "@/styles/globals.css";
import Link from "next/link";
import React from "react";

import { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-zinc-700`}>
        <header className="wrapper h-14 flex flex-col justify-center">
          <nav className="flex items-center gap-3">
            <MenuIcon className="w-6 h-6" />
            <Link href="/">
              <LogoIcon className="w-6 h-6" />
            </Link>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
